name: First github workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Multiline command 
          run: |
            echo "Welcome to Github Actions-Multiline commands"
            ls -ltr
            cat README.md
     #   - name: List files
     #     run: ls -al
        
     #   - name: Read file
     #     run: cat README.md
     # Test